### ISSUE TITLE
problems when plugin folder is outside the main root folder

### ISSUE THREAD

**Issue by Maximus48p** [mantisbt-plugins/Calendar#57] opened 2023-09-27 10:58 UTC
The following folder structure:
```
-- /var/www/html/MantisBT
-- /var/www/html/plugins
```

After installing the Calendar plugin and trying to add an event i get the following error message:

`'include(/var/www/html/plugins/Calendar/pages/../../../bug_view_inc.php): failed to open stream: No such file or directory' in '/var/www/html/plugins/Calendar/pages/event_insert_page.php' line 87`

I have tried to change line 87 to: `include( $g_absolute_path . 'bug_view_inc.php' );`

but that give me an other error:
`'include(/var/www/html/plugins/Calendar/pages/../../../bugnote_view_inc.php): failed to open stream: No such file or directory' in '/var/www/html/mantis/bug_view_inc.php' line 790`

**Comment by brlumen** [comment] 2023-09-27 11:11
It turns out that your plugins folder has been moved to a higher level?

ср, 27 сент. 2023 г., 17:58 Maximus48p ***@***.***>:

**Comment by brlumen** [comment] 2024-06-17 17:17
@Maximus48p, I will include a fix for this error in the next release, but in the meantime, if you don’t want to wait for the release, you can replace 3 lines at the end of the “event_insert_page.php” file with:
```
$t_mantis_dir = config_get_global('absolute_path');

define( 'BUG_VIEW_INC_ALLOW', true );
include( $t_mantis_dir . 'bug_view_inc.php' );
```
This should help fix this error.

**Comment by brlumen** [comment] 2024-06-18 04:47
I reproduced the bug in a test environment by moving the plugins folder up a level:
![image](https://github.com/mantisbt-plugins/Calendar/assets/26021974/d17542eb-0c25-420c-9d04-d8e18150160b)

The error was reproduced:
![image](https://github.com/mantisbt-plugins/Calendar/assets/26021974/f3fdb44f-a3c1-409d-a6a3-8a175cd86929)

After applying the suggested patch, the error no longer reproduces.

**Closed** 2024-06-18 04:48 UTC
Labels: bug
